Repository GO-SOPT-SOLSOL/SOLSOL-iOS, pull requests merged in 2023-05, with the labels that each got.

#6 [Fix] Font 네이밍 수정
  SOLSOL.xcodeproj/project.pbxproj
  SOLSOL/Global/Extension/UIFont+.swift
  SOLSOL/Global/Resources/Font/OneShinhan-Bold.otf
  SOLSOL/Global/Resources/Font/OneShinhan-Light.otf
  SOLSOL/Global/Resources/Font/OneShinhan-Medium.otf
  SOLSOL/Global/Resources/Info.plist
  SOLSOL/Presentation/TransferDetail/bbTableViewCell.swift
Labels: 민재🚀, 희주😺, Fix

#10 [Fix] UIFont+ 피그마에 맞게 사용하기 쉽게 수정
  SOLSOL/Global/Extension/UIFont+.swift
Labels: 민재🚀, Fix

#8 [Feat] HomeViewController 전체적인 구조 구현 (각 section도)
  SOLSOL.xcodeproj/project.pbxproj
  SOLSOL.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SOLSOL.xcodeproj/xcuserdata/byunheejoo.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SOLSOL/Global/Extension/NSObject+.swift
  SOLSOL/Global/Extension/UIColor+.swift
  SOLSOL/Global/Extension/UIFont+.swift
  SOLSOL/Global/Extension/UIView+.swift
  SOLSOL/Presentation/Home/Cells/AdvertisementTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/CategoryTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/DeliveryPackagingTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/FooterButtonTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/MyAccountTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/ShinhanPlusTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/TableViewCell.swift
  SOLSOL/Presentation/Home/Cells/TransferCollectionViewCell.swift
  SOLSOL/Presentation/Home/Cells/TransferTableViewCell.swift
  SOLSOL/Presentation/Home/HomeViewController.swift
  SOLSOL/Presentation/Home/Item.swift
  SOLSOL/Presentation/Home/Section.swift
Labels: 희주😺, Feat✨

#12 [Feat] UI Components 구현
  SOLSOL.xcodeproj/project.pbxproj
  SOLSOL/Application/SceneDelegate.swift
  SOLSOL/Global/Extension/UITabBarController+.swift
  SOLSOL/Global/Literals/ImageLiterals.swift
  SOLSOL/Global/Literals/String.swift
  SOLSOL/Global/UIComponents/SOLButton.swift
  SOLSOL/Global/UIComponents/SOLNavigationBar.swift
  SOLSOL/Presentation/TabBar/SOLTabBarController.swift
  SOLSOL/Presentation/TabBar/SOLTabBarItem.swift
  SOLSOL/Presentation/TabBar/TabVCs/AllMenusViewController.swift
  SOLSOL/Presentation/TabBar/TabVCs/BenefitViewController.swift
  SOLSOL/Presentation/TabBar/TabVCs/MoneyVerseViewController.swift
  SOLSOL/Presentation/TabBar/TabVCs/ProductViewController.swift
  SOLSOL/Presentation/TransferDetail/TransferDetailViewController.swift
Labels: 민재🚀, Feat✨

#18 [Fix] #17 - SOLButton 내부 코드 수정
  SOLSOL/Global/UIComponents/SOLButton.swift
Labels: 민재🚀, Fix

#11 [FEAT] 제목Label, 검색TextField, SegmentedControl 구현
  SOLSOL.xcodeproj/project.pbxproj
  SOLSOL/Global/Extension/UITextField+.swift
  SOLSOL/Global/Extension/UIView+.swift
  SOLSOL/Presentation/Transfer/TransferViewController.swift
  SOLSOL/Presentation/Transfer/Views/TransferView.swift
Labels: 성준👻, Feat✨

#26 [Feat] Transfer section의 CollectionView 구현
  SOLSOL.xcodeproj/project.pbxproj
  SOLSOL/Presentation/Home/Cells/AdvertisementTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/TransferCollectionViewCell.swift
  SOLSOL/Presentation/Home/Cells/TransferListCollectionViewCell.swift
  SOLSOL/Presentation/Home/Cells/TransferTableViewCell.swift
  SOLSOL/Presentation/Home/HomeViewController.swift
  SOLSOL/Presentation/Home/Transfer.swift
  SOLSOL/Presentation/Home/TransferList.swift
Labels: 희주😺, Feat✨

#29 [Feat] #25 SegmentedControl 맞춤버튼 TableView 구현
  SOLSOL.xcodeproj/project.pbxproj
  SOLSOL/Application/SceneDelegate.swift
  SOLSOL/Presentation/Home/HomeViewController.swift
  SOLSOL/Presentation/Transfer/Cells/TransferTableViewCell.swift
  SOLSOL/Presentation/Transfer/Cells/aaTableViewCell.swift
  SOLSOL/Presentation/Transfer/Data.swift
  SOLSOL/Presentation/Transfer/TransferViewController.swift
  SOLSOL/Presentation/Transfer/Views/TransferView.swift
Labels: 성준👻, Feat✨

#28 [Feat] 서버통신 대비 #27
  SOLSOL.xcodeproj/xcuserdata/byunheejoo.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SOLSOL/Presentation/Home/Cells/TransferCollectionViewCell.swift
  SOLSOL/Presentation/Home/Cells/TransferListCollectionViewCell.swift
  SOLSOL/Presentation/Home/Cells/TransferTableViewCell.swift
  SOLSOL/Presentation/Home/HomeViewController.swift
Labels: 희주😺, Feat✨

#32 [Fix] HomeViewController의 레이아웃 수정
  SOLSOL.xcodeproj/xcuserdata/byunheejoo.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SOLSOL/Presentation/Home/Cells/CategoryTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/TransferCollectionViewCell.swift
Labels: 희주😺, Fix

#36 [Feat] #35 - Network Layer 구축
  SOLSOL.xcodeproj/project.pbxproj
  SOLSOL/Global/Resources/Info.plist
  SOLSOL/Network/Base/APIEventLogger.swift
  SOLSOL/Network/Base/APIRequestLoader.swift
  SOLSOL/Network/Base/BaseResponse.swift
  SOLSOL/Network/Base/Config.swift
  SOLSOL/Network/Base/HTTPHeaderField.swift
  SOLSOL/Network/Base/NetworkResult.swift
  SOLSOL/Network/Base/NetworkService.swift
  SOLSOL/Network/Base/TargetType.swift
  SOLSOL/Network/DTO/Home/Request/AccountsListRequestDTO.swift
  SOLSOL/Network/DTO/Home/Response/AccountsListResponseDTO.swift
  SOLSOL/Network/Router/Home/HomeTarget.swift
  SOLSOL/Network/Service/Home/HomeService.swift
  SOLSOL/Presentation/Home/HomeViewController.swift
Labels: 민재🚀, Feat✨

#34 [Feat] #24 - 이체확인 UI 구현
  SOLSOL.xcodeproj/project.pbxproj
  SOLSOL/Global/Literals/SizeLiterals.swift
  SOLSOL/Global/UIComponents/SOLButton.swift
  SOLSOL/Global/Utils/ScreenUtils.swift
  SOLSOL/Presentation/TransferConfirm/TransferConfirmViewController.swift
  SOLSOL/Presentation/TransferConfirm/Views/MemoView.swift
  SOLSOL/Presentation/TransferDetail/TransferDetailViewController.swift
  SOLSOL/Presentation/TransferDetail/Views/NumberPadView.swift
  SOLSOL/Presentation/TransferDetail/Views/TransferDetailView.swift
Labels: 민재🚀, Feat✨

#37 [Feat] #33 - tableView background 클릭 시 키보드 내리기, segmentControl에 View 넣기
  SOLSOL.xcodeproj/project.pbxproj
  SOLSOL/Application/AppDelegate.swift
  SOLSOL/Application/SceneDelegate.swift
  SOLSOL/Global/UIComponents/SOLSegementedControl.swift
  SOLSOL/Presentation/Transfer/Cells/TransferAccountsTableViewCell.swift
  SOLSOL/Presentation/Transfer/Views/TransferView.swift
  SOLSOL/Presentation/Transfer/Views/UserCustomViewController.swift
Labels: 성준👻, Feat✨

#43 [Feat] #38 - 서버통신 완료
  SOLSOL.xcodeproj/project.pbxproj
  SOLSOL.xcodeproj/xcuserdata/byunheejoo.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  SOLSOL/Global/Extension/UICollectionView+.swift
  SOLSOL/Network/DTO/Home/Request/CurrentAccountListRequestDTO.swift
  SOLSOL/Network/DTO/Home/Response/AccountsListResponseDTO.swift
  SOLSOL/Network/DTO/Home/Response/AdvertisementListDTO.swift
  SOLSOL/Network/DTO/Home/Response/CurrentAccountListResponseDTO.swift
  SOLSOL/Network/Router/Home/HomeTarget.swift
  SOLSOL/Network/Service/Home/HomeService.swift
  SOLSOL/Presentation/Home/Advertisement.swift
  SOLSOL/Presentation/Home/Cells/AdvertisementTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/CategoryTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/DeliveryPackagingTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/FooterButtonTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/MyAccountTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/ShinhanPlusTableViewCell.swift
  SOLSOL/Presentation/Home/Cells/TransferCollectionViewCell.swift
  SOLSOL/Presentation/Home/Cells/TransferListCollectionViewCell.swift
  SOLSOL/Presentation/Home/Cells/TransferTableViewCell.swift
  SOLSOL/Presentation/Home/HomeViewController.swift
  SOLSOL/Presentation/Home/Item.swift
  SOLSOL/Presentation/Home/Section.swift
  SOLSOL/Presentation/Home/Transfer.swift
  SOLSOL/Presentation/Home/TransferList.swift
  SOLSOL/Presentation/Home/Views/HomeView.swift
Labels: 희주😺, Feat✨

#45 [Feat] #44 - 이체화면 API 연결
  SOLSOL.xcodeproj/project.pbxproj
  SOLSOL/Global/Enum/Bank.swift
  SOLSOL/Global/Enum/BankBookType.swift
  SOLSOL/Global/Literals/ImageLiterals.swift
  SOLSOL/Global/UIComponents/SOLNavigationBar.swift
  SOLSOL/Network/Base/NetworkService.swift
  SOLSOL/Network/DTO/TransferConfirm/Request/TransferToDTO.swift
  SOLSOL/Network/DTO/TransferConfirm/Response/TransferToResponseDTO.swift
  SOLSOL/Network/DTO/TransferDetail/Response/SingleAccountResponseDTO.swift
  SOLSOL/Network/Router/TransferConfirm/TransferConfirmTarget.swift
  SOLSOL/Network/Router/TransferDetail/TransferDetailTarget.swift
  SOLSOL/Network/Service/TransferConfirm/TransferConfirmService.swift
  SOLSOL/Network/Service/TransferDetail/TransferDetailService.swift
  SOLSOL/Presentation/TransferConfirm/TransferConfirmViewController.swift
  SOLSOL/Presentation/TransferConfirm/TransferModel.swift
  SOLSOL/Presentation/TransferDetail/Model/MyAccount.swift
  SOLSOL/Presentation/TransferDetail/TransferDetailViewController.swift
Labels: 민재🚀, Feat✨

#48 [Feat] #39 - tableView Cell 클릭 시, 화면전환 구현
  SOLSOL/Application/SceneDelegate.swift
  SOLSOL/Presentation/Transfer/TransferViewController.swift
  SOLSOL/Presentation/Transfer/Views/TransferView.swift
  SOLSOL/Presentation/Transfer/Views/UserCustomViewController.swift
Labels: 성준👻, Feat✨

#49 [Chore] #46 - 변경된 모델 기반 API 연결
  SOLSOL.xcodeproj/project.pbxproj
  SOLSOL/Global/Extension/Foundation+/String+.swift
  SOLSOL/Presentation/TransferConfirm/TransferConfirmViewController.swift
  SOLSOL/Presentation/TransferConfirm/TransferModel.swift
  SOLSOL/Presentation/TransferConfirm/Views/MemoView.swift
  SOLSOL/Presentation/TransferDetail/Model/MyAccount.swift
  SOLSOL/Presentation/TransferDetail/TransferDetailViewController.swift
  SOLSOL/Presentation/TransferDetail/ViewModel/TransferDetailViewModel.swift
  SOLSOL/Presentation/TransferDetail/Views/TransferDetailView.swift
Labels: 민재🚀, Chore🧹

#52 [Feat] #51 - 이체화면 엠티뷰 구현
  SOLSOL/Presentation/TransferDetail/TransferDetailViewController.swift
  SOLSOL/Presentation/TransferDetail/ViewModel/TransferDetailViewModel.swift
  SOLSOL/Presentation/TransferDetail/Views/TransferDetailView.swift
Labels: 민재🚀, Feat✨

#54 [Feat] #50 API 서버통신 및 데이터 전달
  SOLSOL.xcodeproj/project.pbxproj
  SOLSOL/Network/Base/NetworkService.swift
  SOLSOL/Network/DTO/Transfer/Request/DeleteRecentAccountRequestDTO.swift
  SOLSOL/Network/DTO/Transfer/Request/RecentSentAccountListRequestDTO.swift
  SOLSOL/Network/DTO/Transfer/Response/DeleteRecentAccountResponseDTO.swift
  SOLSOL/Network/DTO/Transfer/Response/RecentSentAccountListResponseDTO.swift
  SOLSOL/Network/Router/Transfer/TransferTarget.swift
  SOLSOL/Network/Service/Transfer/TransferService.swift
  SOLSOL/Network/Service/TransferConfirm/TransferConfirmService.swift
  SOLSOL/Presentation/Transfer/Cells/TransferAccountsTableViewCell.swift
  SOLSOL/Presentation/Transfer/Data.swift
  SOLSOL/Presentation/Transfer/RecentSentAccountListStruct.swift
  SOLSOL/Presentation/Transfer/TransferViewController.swift
  SOLSOL/Presentation/Transfer/UserCustomViewController.swift
  SOLSOL/Presentation/Transfer/Views/TransferView.swift
Labels: 민재🚀, Feat✨
